import Head from 'next/head'
// import Image from 'next/image'

export default function Home() {
  return (
    <>
      <Head>
        <title>Paul Herasin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className='header'>
        <div className='header-wrap container'>
          <div className='header__right'>
            <div className='header-logo'>
              <span>P</span>aul <span>H</span>.
            </div>
          </div>
          <div className='header__left'>
            <nav className='header-nav'>
              <ul>
                <li><a>About</a></li>
                <li><a>Resume</a></li>
                <li><a>Works</a></li>
                <li><a>Contacts</a></li>
              </ul>
            </nav>
          </div>
        </div>
      </header>
      <main className='main'>
        <div className='background-lines'>
          <div className='background-line'></div>
          <div className='background-line'></div>
          <div className='background-line'></div>
          <div className='background-line'></div>
          <div className='background-line'></div>
        </div>
        <div className='main-screen'>
          <div className='main-screen__wrap container'>
            <h1>Paul Herasin <br></br>
              Frontent-developer
            </h1>
            <div className='main-screen__scroll-btn'></div>
          </div>
        </div>
      </main>
    </>
  )
}
